spring.application.name=shap

spring.datasource.url=${SHAP_DB_URL}
spring.datasource.username=${SHAP_DB_USER}
spring.datasource.password=${SHAP_DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.default_schema=shapdev
spring.jpa.properties.hibernate.format_sql=true
